units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    padding: cy
    tags: 
      1u: true
    footprints:
        choc_hotswap:
          type: choc
          nets:
            from: =colrow
            to: =column_net
          params:
              keycaps: true
              reverse: true
              hotswap: true
        # choc:
        #   type: choc
        #   anchor:
        #     rotate: 180
        #   nets:
        #     from: =colrow
        #     to: =column_net
        #   params:
        #       keycaps: true
        #       reverse: true
        diode:
          type: diode
          nets:
            # from: P3
            # to: P4
            from: =colrow
            to: =row_net
          anchor:
            shift: [0, -4]
        via1:
          type: via
          nets:
            net: =column_net
          anchor:
            shift: [0, 2.5]
        via2:
          type: via
          nets:
            net: =colrow
          anchor:
            shift: [0, 3.75]
  zones:
    matrix:
      # anchor:
      #   rotate: 5
      key.padding: ky
      columns:
        pinky:
          stagger: 0 ky
          spread: kx
          key:
            column_net: P8
            bind: [0,4(kx) + 1,0,1]
        ring:
          stagger: 0.9 ky
          spread: kx
          key:
            column_net: P7
            bind: [0,1,0,1]
        middle:
          stagger: 0.3 ky
          spread: kx
          key:
            column_net: P6
            bind: [0,1,0,1]
        index:
          stagger: -0.3 ky
          spread: kx
          key:
            column_net: P5
            bind: [0,1,0,1]
        inner:
          stagger: -0.3 ky
          spread: kx
          key:
            column_net: P4
            bind: [0,1,0,1]
      rows:
        bottom:
          row_net: P3
        home:
          row_net: P2
        top:
          row_net: P1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.5 kx, -1.6 ky]
      columns:
        near:
          spread: kx
          rotate: -30
          key:
            column_net: P6
        home:
          spread: kx
          key:
            column_net: P5
            bind: [0, 1, 0, 45]
      rows:
        thumb:
          row_net: P9
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx - 0.5 , 1cx - 0.5]
      - type: rectangle
        size: [22, 64]
        anchor:
          ref: matrix_inner_bottom
          shift: [9, -35]
    cutout:
      - type: outline
        name: raw
        fillet: 2
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false  
    preview:
        [keycap_outlines]
pcbs:
  smcboard:
    outlines:
      board:
        outline: cutout
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: matrix_inner_home
          shift: [20, -6]
          rotate: -90
      trrs:
        type: trrs
        anchor:
          ref:
            - matrix_inner_bottom
          shift: [30, -15]
          rotate: 270
        params:
          reverse: true
          symmetric: true
        # The naming of the nets on this footprint is different from the Corne schematics.
        nets:
          A: VCC
          B: VCC
          C: GND
          D: P0
