meta:
  engine: 4.0.2
  version: 1.O
  author: smchunn
  footprint: &switch_footprint "choc"
  switch:
    $extends: presets.choc_v1

presets:
  # These presets provide different layout options
  # Select a preset in the `units` section below
  # Note: The appropriate switch footprint will still need to be set in the `pcb` section
  choc_v1:
    # Key and keycap measures
    kx: cx # spacing between key centers (X-axis)
    ky: cy # spacing between key centers (Y-axis)
    ks: 18.5 # horizontal space between columns (default: 19)
    kp: 17.5 # vertical padding between keys (deafult: 19)
    kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
    kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
    keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
    keych: 16.5 # keycap height (cherry: 18, choc: 16.5)
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: 4.7 # Led Y position relative to the switch center
    led_rotation: 0 # Led rotation
    vertical_underglow_shift: -kp + 7.8  # How much to shift underglow leds tied to keys
    vertical_diode_shift: 0 # How much to shift to avoid overlap
    horizontal_diode_shift: -3.275 
    diode_rotation: 0 # Diode rotation
    vertical_diode_via_shift: -3 # How much to shift to avoid overlap
    horizontal_diode_via_shift: 0 
    switch_rotation: 0 # Hotswap south, led north
units:
  # The following statements will make the content of the preset
  # available in the units context
  $extends: meta.switch

  hand_rotation: 0

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  spacer_radius: 3 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  # Thumb splay
  splay_thumb_middle: 15
  splay_thumb_far: 15
  angle: -18
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
        tags: 
          - key
          - matrix_key
      anchor:
        shift: [150, -120]
      columns:
        pinky:
          key.stagger: 0
          key.col_net: C0
          key.mirror.col_net: C9
        ring:
          key.stagger: 12 
          key.col_net: C1
          key.mirror.col_net: C8
        middle:
          key.stagger: 5
          key.col_net: C2
          key.mirror.col_net: C7
        index:
          key.stagger: -5
          key.col_net: C3
          key.mirror.col_net: C6
        inner:
          key.stagger: -5
          key.col_net: C4
          key.mirror.col_net: C5
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
    thumb:
      key:
        padding: kp
        spread: ks
        stagger: 0
        tags:
          - key
          - thumb_key
      anchor:
        ref: matrix_inner_bottom
        shift: [-2, -21]
      columns:
        index:
          key.splay: -10
          key.col_net: C3
          key.mirror.col_net: C6
        inner:
          key.splay: -15
          key.shift: [2, 0]
          key.col_net: C4
          key.mirror.col_net: C5
      rows:
        extra:
          row_net: R3

    screw_pcb_outer_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: [matrix_ring_top]
          shift: [0, -6.25]
    screw_pcb_outer_bottom:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: [matrix_pinky_bottom]
          shift: [9, -3]
    screw_pcb_inner_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: [matrix_inner_top]
          shift: [0, -6.25]
    screw_pcb_inner_bottom:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: [thumb_index_extra]
          shift: [10, 10]

  rotate: angle
  mirror: &mirror
    ref: matrix_inner_top
    shift: [0.5kx, 0.5ky]
    distance: 25
outlines:
  _pcb:
    - what: polygon
      points:
        - ref: matrix_pinky_bottom
          shift: [-0.5ks, -0.5kp]
        - ref: matrix_pinky_top
          shift: [-0.5ks, 0.5kp]
        - ref: matrix_ring_top
          shift: [-0.5ks, 0.5kp]
        - ref: matrix_middle_top
          shift: [-0.5ks, 0.5kp]
        - ref: matrix_middle_top
          shift: [0.5ks, 0.5kp]
        - ref: matrix_inner_top
          shift: [0.5ks, 0.5kp]
        # - ref: matrix_inner_top
        #   shift: [0.5ks, 0.1kp]

        # - ref: mirror_matrix_inner_top
        #   shift: [0.5ks, 0.1kp]
        - ref: mirror_matrix_inner_top
          shift: [0.5ks, 0.5kp]
        - ref: mirror_matrix_middle_top
          shift: [0.5ks, 0.5kp]
        - ref: mirror_matrix_middle_top
          shift: [-0.5ks, 0.5kp]
        - ref: mirror_matrix_ring_top
          shift: [-0.5ks, 0.5kp]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5ks, 0.5kp]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5ks, -0.5kp]

        - ref: mirror_matrix_pinky_bottom
          shift: [2.2ks, -0.5kp]
        - ref: mirror_thumb_index_extra
          shift: [-0.5ks, -0.5kp]
        - ref: mirror_thumb_index_extra
          shift: [0.5ks, -0.5kp]
        - ref: mirror_thumb_inner_extra
          shift: [0.5ks, -0.5kp]
        # - ref: mirror_matrix_inner_bottom
        #   shift: [1.58ks, -0.95kp]

        # - ref: matrix_inner_bottom
        #   shift: [1.58ks, -0.95kp]
        - ref: thumb_inner_extra
          shift: [0.5ks, -0.5kp]
        - ref: thumb_index_extra
          shift: [0.5ks, -0.5kp]
        - ref: thumb_index_extra
          shift: [-0.5ks, -0.5kp]
        - ref: matrix_pinky_bottom
          shift: [2.2ks, -0.5kp]
      fillet: 3

  _case_inner_edge:
    - what: outline
      name: _pcb
      expand: .5
      fillet: .5
  _case_outer_edge:
    - what: outline
      name: _pcb
      expand: 2.1
      fillet: 2.1
  _battery_cutout:
    - what: rectangle
      size: [28, 22]
      adjust:
        aggregate.parts:
          - ref: matrix_inner_bottom
          - ref: mirror_matrix_inner_bottom
        shift: [0, -6]
  _keycap_outlines:
    - what: rectangle
      fillet: 2
      where: [key]
      size: [keycw, keych]
    - what: rectangle
      fillet: 2
      where: [key_1_5u]
      size: [keycw*1.5, keych]
  _switch_cutouts:
    - what: rectangle
      where: /key/
      size: [kcow, kcoh]
  _bat_sw_safezone_out:
    - what: rectangle
      adjust:
        aggregate.parts:
          - ref: matrix_inner_top
          - ref: mirror_matrix_inner_top
        shift: [-25.5, 11.9]
        rotate: 146.9
      size: [8, 10]
  _pcm_12_cutout:
    - what: rectangle
      size: [1.8, 6]
      adjust:
        aggregate.parts:
          - ref: matrix_inner_top
          - ref: mirror_matrix_inner_top
        shift: [-17, -11.75]
  _reset_cutout:
    - what: circle 
      radius: 0.75
      adjust:
        aggregate.parts:
          - ref: matrix_inner_top
          - ref: mirror_matrix_inner_top
        shift: [6, -20]
  _mcu_safezone_out:
    - what: rectangle
      adjust:
        aggregate.parts:
          - ref: matrix_inner_top
          - ref: mirror_matrix_inner_top
        shift: [0, 8]
        rotate: 0
      size: [14, 5]
  _screws:
    - what: circle
      where: /screw_pcb/
      radius: screw_radius
  _spacers:
    - what: circle
      where: /screw_pcb/
      radius: spacer_radius
  _plate_outline:
    - what: outline
      name: _pcb
      # fillet: fillet_radius
    - what: outline
      name: _switch_cutouts
      operation: subtract
  plate:
    - _plate_outline
  board:
    - _pcb
    - -_battery_cutout
  preview:
    - _pcb
    - ^_keycap_outlines
pcbs:
  smcboard_mono:
    outlines:
      pcb:
        outline: board
      keycaps:
        outline: _keycap_outlines 
        layer: Eco1.User
      power_slider:
        outline: _pcm_12_cutout 
        layer: Eco1.User
      reset_cutout:
        outline: _reset_cutout 
        layer: Eco1.User
      # NiceNanoV2
    footprints:
      mcu:
        what: seeed_xiao
        adjust:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [0, -4.45]
          rotate: 0
        params:
          side: 'B'
          P0: R0
          P1: R1
          P2: R2
          P3: R3
          P4: C5
          P5: C6
      # io expander
      ioexp:
        what: mcp23s08_ssop
        adjust:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [-2, -20]
          rotate: 90
        params:
          side: 'B'
          SCK: P8
          SI: P10
          SO: P9
          A1: GND
          A0: GND
          RST: VCC
          CS: P7
          VSS: GND
          VDD: VCC
          GP0: C7
          GP1: C8
          GP2: C9
          GP3: C0
          GP4: C1
          GP5: C2
          GP6: C3
          GP7: C4
      # Reset Button
      reset:
        what: b3u1000p
        adjust:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [6, -20]
          rotate: -90
        params:
          r1: RST
          r2: GND
      # Slider switch - Power
      pcm12:
        what: pcm12
        adjust:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [-14.5, -11.75]
          rotate: -90 
        params:
          reverse: false
          flip: true
          front: false
          from: pos
          to: BATP
      # Battery JST Connector
      bat:
        what: bat
        params:
          neg: BATN
        adjust:
          aggregate.parts:
            - ref: matrix_inner_top
            - ref: mirror_matrix_inner_top
          shift: [-10, -17]
          rotate: 90
      # Switch FP
      switches:
        what: *switch_footprint
        where: /key/ 
        params:
          reverse: false
          hotswap: true
          from: "{{colrow}}"
          to: "{{col_net}}"
          # The following parameters are specific to choc_v2_hotswap
          # outer_pad_width_front: 1.6
          # outer_pad_width_back: 1.6
        adjust:
          rotate: switch_rotation
          resist: true
      diodes:
        what: combo_diode
        where: /key/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: B
        adjust:
          shift: [horizontal_diode_shift,vertical_diode_shift]
          rotate: 90 + diode_rotation
          resist: true
      diode_via:
        what: via 
        where: /key/
        params:
          net: "{{row_net}}"
        adjust:
          shift: [horizontal_diode_via_shift,vertical_diode_via_shift]
      # Mounting Holes
      holeLTL:
        what: mountingholestandoff
        adjust:
          ref: [matrix_ring_top]
          shift: [0, -6.25]
      holeLBL:
        what: mountingholestandoff
        adjust:
          ref: [matrix_pinky_bottom]
          shift: [9, -3]
      holeLTR:
        what: mountingholestandoff
        adjust:
          ref: [matrix_inner_top]
          shift: [0, -6.25]
      holeLBR:
        what: mountingholestandoff
        adjust:
          ref: [thumb_index_extra]
          shift: [10, 10]
      holeRTL:
        what: mountingholestandoff
        adjust:
          ref: [mirror_matrix_ring_top]
          shift: [0, -6.25]
      holeRBL:
        what: mountingholestandoff
        adjust:
          ref: [mirror_matrix_pinky_bottom]
          shift: [9, -3]
      holeRTR:
        what: mountingholestandoff
        adjust:
          ref: [mirror_matrix_inner_top]
          shift: [0, -6.25]
      holeRBR:
        what: mountingholestandoff
        adjust:
          ref: [mirror_thumb_index_extra]
          shift: [10, 10]
cases:
  bottom:
    # - name: _pcb
    #   extrude: 3
    - name: _case_outer_edge
      extrude: 3
  _screw_holes:
    - name: _screws
      extrude: 8
  _screw_clearance:
    - name: _spacers
      extrude: 1.5
  _outerWall:
    - name: _case_outer_edge
      extrude: 8.7
  _innerWall:
    - name: _case_inner_edge
      extrude: 8.7
  _bat_sw_safezone:
    - name: _bat_sw_safezone_out
      extrude: 3
      shift: [0,0,4]
  _mcu_safezone:
    - name: _mcu_safezone_out
      extrude: 7
      shift: [0,0,0.85]
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  plate:
    - name: _plate_outline
      extrude: 1.4
  case:
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add
    - what: case
      name: _screw_clearance
      operation: subtract
    - what: case
      name: _screw_holes
      operation: subtract
    - what: case
      name: _mcu_safezone
      operation: subtract
    - what: case
      name: _bat_sw_safezone
      operaton: subtract
